### ISSUE TITLE
값의 계산

### ISSUE THREAD

**Issue by 20chan** [phillyai/shrew#5]
가장 중요하고 먼저 생각을 했어야 하는 부분이다.
물론 모든 값이 상수이고 언어 내에서만 만들 수 있는 패턴은 모두 순수한 함수(패턴) 밖에 없으니까 값의 계산 시간이 크게 신경쓰지 않아도 될 거 같지만 순수하지 않은 빌트인 함수가 추가된다면 말이 달라진다.

**Comment by phillyai** [comment]
79502201979765ddf31e159fd9c720be4044a024 커밋 기준으로 값의 계산 타이밍은 다음과 같다.

https://github.com/phillyai/shrew/blob/79502201979765ddf31e159fd9c720be4044a024/shrew/Engine.cs#L79-81 에서 볼 수 있듯이 모든 값의 계산이 lazy 하다.

`a = 1` `b = 2` `c = a + b` 라면 `c`의 값을 계산할때마다 `a + b`를 계산할 것이다.
물론 `get` 키워드를 사용하면  값을 바로 계산할 수 있긴 하다. `c = get (a + b)` 는 코드는 선언시 `c`의 값을 계산하여 `c` 는 3의 값을 가지는 리터럴 노드를 가르킬 것이다.

현재까지는 이렇게 모든 패턴이 게으르게 계산된다. 이러한 방식이 괜찮을까?

**Comment by phillyai** [comment]
파라미터를 받지 않는 패턴을 어렵게 생각하다 보니 헷갈렸던 거 같다.
```
concat a b = a ++ b
w = "wow"
read = concat readline "!"
wow = concat w "!"
```
위 코드에서 read 와 wow 의 작동은 일반적인 언어에서는 달라보이지만 여기서는 `w` 나 `readline` 이나 똑같이 0개의 파라미터를 받는 패턴으로 단순히 순수하다/순수하지 않다의 차이만이 있을 뿐이다.
여기서 lazy 하게 값을 계산한다고 해서 문제될 일은 없어 보인다. 적어도 아직까지는..
